import { ElementType } from 'react';

export type IPolymorphicComponent =
  | 'div'
  | 'section'
  | 'article'
  | 'aside'
  | 'header'
  | 'footer'
  | 'main'
  | 'nav'
  | 'form'
  | 'fieldset'
  | 'legend'
  | 'label'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'p'
  | 'span'
  | 'strong'
  | 'em'
  | 'b'
  | 'i'
  | 'u'
  | 'small'
  | 'sub'
  | 'sup'
  | 'code'
  | 'pre'
  | 'blockquote'
  | 'ol'
  | 'ul'
  | 'li'
  | 'dl'
  | 'dt'
  | 'dd'
  | 'a'
  | 'button'
  | 'input'
  | 'textarea'
  | 'select'
  | 'option'
  | 'img'
  | 'picture'
  | 'source'
  | 'video'
  | 'audio'
  | 'table'
  | 'thead'
  | 'tbody'
  | 'tfoot'
  | 'tr'
  | 'td'
  | 'th'
  | 'caption'
  | 'colgroup'
  | 'col';

export const HTML_ELEMENTS: Record<IPolymorphicComponent, ElementType> = {
  div: 'div',
  section: 'section',
  article: 'article',
  aside: 'aside',
  header: 'header',
  footer: 'footer',
  main: 'main',
  nav: 'nav',
  form: 'form',
  fieldset: 'fieldset',
  legend: 'legend',
  label: 'label',
  h1: 'h1',
  h2: 'h2',
  h3: 'h3',
  h4: 'h4',
  h5: 'h5',
  h6: 'h6',
  p: 'p',
  span: 'span',
  strong: 'strong',
  em: 'em',
  b: 'b',
  i: 'i',
  u: 'u',
  small: 'small',
  sub: 'sub',
  sup: 'sup',
  code: 'code',
  pre: 'pre',
  blockquote: 'blockquote',
  ol: 'ol',
  ul: 'ul',
  li: 'li',
  dl: 'dl',
  dt: 'dt',
  dd: 'dd',
  a: 'a',
  button: 'button',
  input: 'input',
  textarea: 'textarea',
  select: 'select',
  option: 'option',
  img: 'img',
  picture: 'picture',
  source: 'source',
  video: 'video',
  audio: 'audio',
  table: 'table',
  thead: 'thead',
  tbody: 'tbody',
  tfoot: 'tfoot',
  tr: 'tr',
  td: 'td',
  th: 'th',
  caption: 'caption',
  colgroup: 'colgroup',
  col: 'col',
};
